remote_theme: poole/hyde
permalink:           pretty

# Setup
title:               Eisvogel
tagline:             A clean pandoc LaTeX template to convert your markdown files to PDF or LaTeX.
url:                 http://wandmalfarbe.github.io/jekyll-theme-test
baseurl:             /jekyll-theme-test/

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              "@Wandmalfarbe"