remote_theme: pmarsceill/just-the-docs
permalink:           pretty

# Setup
title:               Eisvogel
tagline:             A clean pandoc LaTeX template to convert your markdown files to PDF or LaTeX.
url:                 http://wandmalfarbe.github.io/jekyll-theme-test
baseurl:             /jekyll-theme-test/